/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marianne
 */
public class CoffeeDashboad extends javax.swing.JFrame {

     private String coffeeSize; 
    private int coffeeQuantity; 
    private double coffeePrice; 

    public CoffeeDashboad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AmericanoBTG = new javax.swing.ButtonGroup();
        BrewedBTG = new javax.swing.ButtonGroup();
        CacaoBTG = new javax.swing.ButtonGroup();
        ConPannaBTG = new javax.swing.ButtonGroup();
        CortadoBTG = new javax.swing.ButtonGroup();
        EspressoBTG = new javax.swing.ButtonGroup();
        HazelNutBTG = new javax.swing.ButtonGroup();
        LatteBTG = new javax.swing.ButtonGroup();
        CaramelBTG = new javax.swing.ButtonGroup();
        DarkChocolateBTG = new javax.swing.ButtonGroup();
        WhiteMochaBTG = new javax.swing.ButtonGroup();
        FlatWhiteBTG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Americano = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CoffeeName8 = new javax.swing.JLabel();
        CoffeePrice8 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        CoffeSize8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Q1 = new javax.swing.JComboBox<>();
        EL1 = new javax.swing.JCheckBox();
        s1 = new javax.swing.JCheckBox();
        m1 = new javax.swing.JCheckBox();
        L1 = new javax.swing.JCheckBox();
        P1 = new javax.swing.JTextField();
        add1 = new javax.swing.JButton();
        Brewed = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CoffeeName14 = new javax.swing.JLabel();
        CoffeePrice14 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        CoffeSize14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Q2 = new javax.swing.JComboBox<>();
        EL2 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        m2 = new javax.swing.JCheckBox();
        L2 = new javax.swing.JCheckBox();
        P2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        Cacao = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CoffeeName15 = new javax.swing.JLabel();
        CoffeePrice15 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        CoffeSize15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Q3 = new javax.swing.JComboBox<>();
        EL3 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        m3 = new javax.swing.JCheckBox();
        L3 = new javax.swing.JCheckBox();
        P3 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        ConPanna = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CoffeeName16 = new javax.swing.JLabel();
        CoffeePrice16 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        CoffeSize16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Q4 = new javax.swing.JComboBox<>();
        EL4 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        m4 = new javax.swing.JCheckBox();
        L4 = new javax.swing.JCheckBox();
        P4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        Cortado = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CoffeeName17 = new javax.swing.JLabel();
        CoffeePrice17 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        CoffeSize17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Q8 = new javax.swing.JComboBox<>();
        EL8 = new javax.swing.JCheckBox();
        s8 = new javax.swing.JCheckBox();
        m8 = new javax.swing.JCheckBox();
        L8 = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        P8 = new javax.swing.JTextField();
        Espresso = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CoffeeName18 = new javax.swing.JLabel();
        CoffeePrice18 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        CoffeSize18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Q7 = new javax.swing.JComboBox<>();
        EL7 = new javax.swing.JCheckBox();
        s7 = new javax.swing.JCheckBox();
        m7 = new javax.swing.JCheckBox();
        L7 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        P7 = new javax.swing.JTextField();
        Hazelnut = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        CoffeeName19 = new javax.swing.JLabel();
        CoffeePrice19 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        CoffeSize19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Q6 = new javax.swing.JComboBox<>();
        EL6 = new javax.swing.JCheckBox();
        s6 = new javax.swing.JCheckBox();
        m6 = new javax.swing.JCheckBox();
        L6 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        P6 = new javax.swing.JTextField();
        Latte = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        CoffeeName20 = new javax.swing.JLabel();
        CoffeePrice20 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        CoffeSize20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Q5 = new javax.swing.JComboBox<>();
        EL5 = new javax.swing.JCheckBox();
        s5 = new javax.swing.JCheckBox();
        m5 = new javax.swing.JCheckBox();
        L5 = new javax.swing.JCheckBox();
        jButton8 = new javax.swing.JButton();
        P5 = new javax.swing.JTextField();
        Caramel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        CoffeeName21 = new javax.swing.JLabel();
        CoffeePrice21 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        CoffeSize21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Q9 = new javax.swing.JComboBox<>();
        EL9 = new javax.swing.JCheckBox();
        s9 = new javax.swing.JCheckBox();
        m9 = new javax.swing.JCheckBox();
        L9 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        P9 = new javax.swing.JTextField();
        DarkChocolate = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CoffeeName22 = new javax.swing.JLabel();
        CoffeePrice22 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        CoffeSize22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Q10 = new javax.swing.JComboBox<>();
        EL10 = new javax.swing.JCheckBox();
        s10 = new javax.swing.JCheckBox();
        m10 = new javax.swing.JCheckBox();
        L10 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        P10 = new javax.swing.JTextField();
        WhiteMocha = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        CoffeeName23 = new javax.swing.JLabel();
        CoffeePrice23 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        CoffeSize23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Q11 = new javax.swing.JComboBox<>();
        EL11 = new javax.swing.JCheckBox();
        s11 = new javax.swing.JCheckBox();
        m11 = new javax.swing.JCheckBox();
        L11 = new javax.swing.JCheckBox();
        CoffeSize26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        P11 = new javax.swing.JTextField();
        FlatWhite = new javax.swing.JPanel();
        CoffeeName25 = new javax.swing.JLabel();
        CoffeePrice25 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        CoffeSize25 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Q12 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        EL12 = new javax.swing.JCheckBox();
        s12 = new javax.swing.JCheckBox();
        m12 = new javax.swing.JCheckBox();
        L12 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        P12 = new javax.swing.JTextField();
        BackGroundImage2 = new javax.swing.JLabel();
        CoffeeMenu = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        BackGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(230, 183, 153));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Americano.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Americano.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N
        Americano.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName8.setText("Name:");
        Americano.add(CoffeeName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice8.setText("Price");
        Americano.add(CoffeePrice8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel52.setText("Quantity");
        Americano.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize8.setText("Size");
        Americano.add(CoffeSize8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel2.setText("Americano");
        Americano.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1ActionPerformed(evt);
            }
        });
        Americano.add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        AmericanoBTG.add(EL1);
        EL1.setText("Extra Large");
        EL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL1ActionPerformed(evt);
            }
        });
        Americano.add(EL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        AmericanoBTG.add(s1);
        s1.setText("Small");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        Americano.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        AmericanoBTG.add(m1);
        m1.setText("Medium");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        Americano.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        AmericanoBTG.add(L1);
        L1.setText("Large");
        L1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1ActionPerformed(evt);
            }
        });
        Americano.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        P1.setText("150");
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });
        Americano.add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        add1.setText("Add");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        Americano.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jPanel1.add(Americano, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 211, 320));

        Brewed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Brewed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Brewed Coffee.jpg"))); // NOI18N
        Brewed.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName14.setText("Name:");
        Brewed.add(CoffeeName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice14.setText("Price");
        Brewed.add(CoffeePrice14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel54.setText("Quantity");
        Brewed.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize14.setText("Size");
        Brewed.add(CoffeSize14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel5.setText("Brewed ");
        Brewed.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2ActionPerformed(evt);
            }
        });
        Brewed.add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        BrewedBTG.add(EL2);
        EL2.setText("Extra Large");
        EL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL2ActionPerformed(evt);
            }
        });
        Brewed.add(EL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        BrewedBTG.add(s2);
        s2.setText("Small");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        Brewed.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        BrewedBTG.add(m2);
        m2.setText("Medium");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        Brewed.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        BrewedBTG.add(L2);
        L2.setText("Large");
        L2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2ActionPerformed(evt);
            }
        });
        Brewed.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        P2.setText("150");
        P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ActionPerformed(evt);
            }
        });
        Brewed.add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton11.setText("Add");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Brewed.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        jPanel1.add(Brewed, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 13, 211, 320));

        Cacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Cacao.jpg"))); // NOI18N
        Cacao.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName15.setText("Name:");
        Cacao.add(CoffeeName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice15.setText("Price");
        Cacao.add(CoffeePrice15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel56.setText("Quantity");
        Cacao.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize15.setText("Size");
        Cacao.add(CoffeSize15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel8.setText("Cacao");
        Cacao.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3ActionPerformed(evt);
            }
        });
        Cacao.add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        CacaoBTG.add(EL3);
        EL3.setText("Extra Large");
        EL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL3ActionPerformed(evt);
            }
        });
        Cacao.add(EL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        CacaoBTG.add(s3);
        s3.setText("Small");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        Cacao.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        CacaoBTG.add(m3);
        m3.setText("Medium");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });
        Cacao.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        CacaoBTG.add(L3);
        L3.setText("Large");
        L3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3ActionPerformed(evt);
            }
        });
        Cacao.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        P3.setText("150");
        P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ActionPerformed(evt);
            }
        });
        Cacao.add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Cacao.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        jPanel1.add(Cacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 13, 211, 320));

        ConPanna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConPanna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Con panna coffee.jpg"))); // NOI18N
        ConPanna.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName16.setText("Name:");
        ConPanna.add(CoffeeName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice16.setText("Price");
        ConPanna.add(CoffeePrice16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel88.setText("Quantity");
        ConPanna.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize16.setText("Size");
        ConPanna.add(CoffeSize16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel11.setText("Con Panna");
        ConPanna.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4ActionPerformed(evt);
            }
        });
        ConPanna.add(Q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        ConPannaBTG.add(EL4);
        EL4.setText("Extra Large");
        ConPanna.add(EL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        ConPannaBTG.add(s4);
        s4.setText("Small");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        ConPanna.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        ConPannaBTG.add(m4);
        m4.setText("Medium");
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        ConPanna.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        ConPannaBTG.add(L4);
        L4.setText("Large");
        ConPanna.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        P4.setText("150");
        P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4ActionPerformed(evt);
            }
        });
        ConPanna.add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        ConPanna.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        jPanel1.add(ConPanna, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 13, 211, 320));

        Cortado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cortado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Cortado coffee.jpg"))); // NOI18N
        Cortado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName17.setText("Name:");
        Cortado.add(CoffeeName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice17.setText("Price");
        Cortado.add(CoffeePrice17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel90.setText("Quantity");
        Cortado.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize17.setText("Size");
        Cortado.add(CoffeSize17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel14.setText("Cortado");
        Cortado.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q8ActionPerformed(evt);
            }
        });
        Cortado.add(Q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        CortadoBTG.add(EL8);
        EL8.setText("Extra Large");
        EL8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL8ActionPerformed(evt);
            }
        });
        Cortado.add(EL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        CortadoBTG.add(s8);
        s8.setText("Small");
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });
        Cortado.add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        CortadoBTG.add(m8);
        m8.setText("Medium");
        m8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m8ActionPerformed(evt);
            }
        });
        Cortado.add(m8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        CortadoBTG.add(L8);
        L8.setText("Large");
        L8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L8ActionPerformed(evt);
            }
        });
        Cortado.add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Cortado.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P8.setText("150");
        P8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P8ActionPerformed(evt);
            }
        });
        Cortado.add(P8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(Cortado, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 371, 211, 338));

        Espresso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Espresso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Espresso coffee.jpg"))); // NOI18N
        Espresso.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName18.setText("Name:");
        Espresso.add(CoffeeName18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice18.setText("Price");
        Espresso.add(CoffeePrice18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel92.setText("Quantity");
        Espresso.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize18.setText("Size");
        Espresso.add(CoffeSize18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel17.setText("Espresso");
        Espresso.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7ActionPerformed(evt);
            }
        });
        Espresso.add(Q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        EspressoBTG.add(EL7);
        EL7.setText("Extra Large");
        EL7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL7ActionPerformed(evt);
            }
        });
        Espresso.add(EL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        EspressoBTG.add(s7);
        s7.setText("Small");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });
        Espresso.add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        EspressoBTG.add(m7);
        m7.setText("Medium");
        m7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m7ActionPerformed(evt);
            }
        });
        Espresso.add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        EspressoBTG.add(L7);
        L7.setText("Large");
        L7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L7ActionPerformed(evt);
            }
        });
        Espresso.add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Espresso.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P7.setText("150");
        P7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P7ActionPerformed(evt);
            }
        });
        Espresso.add(P7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(Espresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 371, 211, 338));

        Hazelnut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Hazelnut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Hazelnut coffee.jpg"))); // NOI18N
        Hazelnut.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName19.setText("Name:");
        Hazelnut.add(CoffeeName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice19.setText("Price");
        Hazelnut.add(CoffeePrice19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel94.setText("Quantity");
        Hazelnut.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize19.setText("Size");
        Hazelnut.add(CoffeSize19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel20.setText("Hazelnut ");
        Hazelnut.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q6ActionPerformed(evt);
            }
        });
        Hazelnut.add(Q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        HazelNutBTG.add(EL6);
        EL6.setText("Extra Large");
        EL6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL6ActionPerformed(evt);
            }
        });
        Hazelnut.add(EL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        HazelNutBTG.add(s6);
        s6.setText("Small");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        Hazelnut.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        HazelNutBTG.add(m6);
        m6.setText("Medium");
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        Hazelnut.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        HazelNutBTG.add(L6);
        L6.setText("Large");
        L6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L6ActionPerformed(evt);
            }
        });
        Hazelnut.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Hazelnut.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P6.setText("150");
        P6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P6ActionPerformed(evt);
            }
        });
        Hazelnut.add(P6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(Hazelnut, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 371, 211, 338));

        Latte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Latte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Latte coffee.jpg"))); // NOI18N
        Latte.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName20.setText("Name:");
        Latte.add(CoffeeName20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice20.setText("Price");
        Latte.add(CoffeePrice20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel96.setText("Quantity");
        Latte.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize20.setText("Size");
        Latte.add(CoffeSize20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel23.setText("Latte");
        Latte.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5ActionPerformed(evt);
            }
        });
        Latte.add(Q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        LatteBTG.add(EL5);
        EL5.setText("Extra Large");
        EL5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL5ActionPerformed(evt);
            }
        });
        Latte.add(EL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        LatteBTG.add(s5);
        s5.setText("Small");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        Latte.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        LatteBTG.add(m5);
        m5.setText("Medium");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });
        Latte.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        LatteBTG.add(L5);
        L5.setText("Large");
        L5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5ActionPerformed(evt);
            }
        });
        Latte.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Latte.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P5.setText("150");
        P5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5ActionPerformed(evt);
            }
        });
        Latte.add(P5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(Latte, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 371, 211, 338));

        Caramel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Caramel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/caramel.jpg"))); // NOI18N
        Caramel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName21.setText("Name:");
        Caramel.add(CoffeeName21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice21.setText("Price");
        Caramel.add(CoffeePrice21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel98.setText("Quantity");
        Caramel.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize21.setText("Size");
        Caramel.add(CoffeSize21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel26.setText("Caramel");
        Caramel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q9ActionPerformed(evt);
            }
        });
        Caramel.add(Q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        CaramelBTG.add(EL9);
        EL9.setText("Extra Large");
        EL9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL9ActionPerformed(evt);
            }
        });
        Caramel.add(EL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        CaramelBTG.add(s9);
        s9.setText("Small");
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });
        Caramel.add(s9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        CaramelBTG.add(m9);
        m9.setText("Medium");
        m9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m9ActionPerformed(evt);
            }
        });
        Caramel.add(m9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        CaramelBTG.add(L9);
        L9.setText("Large");
        L9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L9ActionPerformed(evt);
            }
        });
        Caramel.add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Caramel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P9.setText("150");
        P9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P9ActionPerformed(evt);
            }
        });
        Caramel.add(P9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(Caramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 743, 211, 338));

        DarkChocolate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DarkChocolate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/dark chocolate.jpg"))); // NOI18N
        DarkChocolate.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName22.setText("Name:");
        DarkChocolate.add(CoffeeName22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice22.setText("Price");
        DarkChocolate.add(CoffeePrice22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel100.setText("Quantity");
        DarkChocolate.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize22.setText("Size");
        DarkChocolate.add(CoffeSize22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel29.setText("Dark  Chocolate");
        DarkChocolate.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q10ActionPerformed(evt);
            }
        });
        DarkChocolate.add(Q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        DarkChocolateBTG.add(EL10);
        EL10.setText("Extra Large");
        EL10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL10ActionPerformed(evt);
            }
        });
        DarkChocolate.add(EL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        DarkChocolateBTG.add(s10);
        s10.setText("Small");
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });
        DarkChocolate.add(s10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        DarkChocolateBTG.add(m10);
        m10.setText("Medium");
        m10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m10ActionPerformed(evt);
            }
        });
        DarkChocolate.add(m10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        DarkChocolateBTG.add(L10);
        L10.setText("Large");
        L10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L10ActionPerformed(evt);
            }
        });
        DarkChocolate.add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        DarkChocolate.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P10.setText("150");
        P10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P10ActionPerformed(evt);
            }
        });
        DarkChocolate.add(P10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(DarkChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 743, 211, 338));

        WhiteMocha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhiteMocha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/white mocha.jpg"))); // NOI18N
        WhiteMocha.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName23.setText("Name:");
        WhiteMocha.add(CoffeeName23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice23.setText("Price");
        WhiteMocha.add(CoffeePrice23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel102.setText("Quantity");
        WhiteMocha.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize23.setText("Size");
        WhiteMocha.add(CoffeSize23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel32.setText("White Mocha");
        WhiteMocha.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        Q11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Q11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q11ActionPerformed(evt);
            }
        });
        WhiteMocha.add(Q11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        WhiteMochaBTG.add(EL11);
        EL11.setText("Extra Large");
        EL11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL11ActionPerformed(evt);
            }
        });
        WhiteMocha.add(EL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        WhiteMochaBTG.add(s11);
        s11.setText("Small");
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });
        WhiteMocha.add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        WhiteMochaBTG.add(m11);
        m11.setText("Medium");
        m11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m11ActionPerformed(evt);
            }
        });
        WhiteMocha.add(m11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        WhiteMochaBTG.add(L11);
        L11.setText("Large");
        L11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L11ActionPerformed(evt);
            }
        });
        WhiteMocha.add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        CoffeSize26.setText("Size");
        WhiteMocha.add(CoffeSize26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        WhiteMocha.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P11.setText("150");
        P11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P11ActionPerformed(evt);
            }
        });
        WhiteMocha.add(P11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(WhiteMocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 743, 211, 338));

        FlatWhite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoffeeName25.setText("Name:");
        FlatWhite.add(CoffeeName25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice25.setText("Price");
        FlatWhite.add(CoffeePrice25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel107.setText("Quantity");
        FlatWhite.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        CoffeSize25.setText("Size");
        FlatWhite.add(CoffeSize25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel34.setText("Flat White");
        FlatWhite.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        Q12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Q12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q12ActionPerformed(evt);
            }
        });
        FlatWhite.add(Q12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Flat white coffee.jpg"))); // NOI18N
        FlatWhite.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        FlatWhiteBTG.add(EL12);
        EL12.setText("Extra Large");
        EL12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EL12ActionPerformed(evt);
            }
        });
        FlatWhite.add(EL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        FlatWhiteBTG.add(s12);
        s12.setText("Small");
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        FlatWhite.add(s12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        FlatWhiteBTG.add(m12);
        m12.setText("Medium");
        m12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m12ActionPerformed(evt);
            }
        });
        FlatWhite.add(m12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        FlatWhiteBTG.add(L12);
        L12.setText("Large");
        L12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L12ActionPerformed(evt);
            }
        });
        FlatWhite.add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        FlatWhite.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 20));

        P12.setText("150");
        P12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P12ActionPerformed(evt);
            }
        });
        FlatWhite.add(P12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(FlatWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 740, 210, 340));

        BackGroundImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/brgcoffee.jpg"))); // NOI18N
        BackGroundImage2.setText("jLabel38");
        jPanel1.add(BackGroundImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 1120));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 1010, 570));

        CoffeeMenu.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        CoffeeMenu.setForeground(new java.awt.Color(255, 255, 255));
        CoffeeMenu.setText("Coffee Menu");
        getContentPane().add(CoffeeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 55));

        jButton17.setText("Coffee");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jButton18.setText("Tea");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 70, -1));

        jButton19.setText("Drinks");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, -1, -1));

        jButton20.setText("Pastry");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, -1, -1));

        jButton21.setText("Dishes");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, -1, -1));

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton12.setText("Total");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 150, 50));

        BackGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/brgcoffee.jpg"))); // NOI18N
        getContentPane().add(BackGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m12ActionPerformed
        // TODO add your handling code here:
        P12.setText("160");
    }//GEN-LAST:event_m12ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
        P1.setText("150");
    }//GEN-LAST:event_s1ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
        P1.setText("160");
        
    }//GEN-LAST:event_m1ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
        // TODO add your handling code here:
        P11.setText("150");
    }//GEN-LAST:event_s11ActionPerformed

    private void m11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m11ActionPerformed
        // TODO add your handling code here:
        P11.setText("160");
    }//GEN-LAST:event_m11ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1ActionPerformed

    private void EL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL1ActionPerformed
        // TODO add your handling code here:
        P1.setText("180");
    }//GEN-LAST:event_EL1ActionPerformed

    private void L1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1ActionPerformed
        // TODO add your handling code here:
        P1.setText("170");
    }//GEN-LAST:event_L1ActionPerformed

    private void Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1ActionPerformed
        int p = Integer.parseInt(P1.getText());
        int q = Integer.parseInt((String) Q1.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P1.setText(t);
    }//GEN-LAST:event_Q1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
        P2.setText("150");
    }//GEN-LAST:event_s2ActionPerformed

    private void EL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL2ActionPerformed
        // TODO add your handling code here:
        P2.setText("180");
    }//GEN-LAST:event_EL2ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
           P2.setText("160");
    }//GEN-LAST:event_m2ActionPerformed

    private void Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P2.getText());
        int q = Integer.parseInt((String) Q2.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P2.setText(t);
    }//GEN-LAST:event_Q2ActionPerformed

    private void L2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2ActionPerformed
        // TODO add your handling code here:
           P2.setText("170");
    }//GEN-LAST:event_L2ActionPerformed

    private void P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:..
        P3.setText("150");
    }//GEN-LAST:event_s3ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
        P3.setText("160");
    }//GEN-LAST:event_m3ActionPerformed

    private void L3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3ActionPerformed
        // TODO add your handling code here:
        P3.setText("170");
    }//GEN-LAST:event_L3ActionPerformed

    private void EL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL3ActionPerformed
        // TODO add your handling code here:
        P3.setText("180");
    }//GEN-LAST:event_EL3ActionPerformed

    private void Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P3.getText());
        int q = Integer.parseInt((String) Q3.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P3.setText(t);
    }//GEN-LAST:event_Q3ActionPerformed

    private void Q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P4.getText());
        int q = Integer.parseInt((String) Q4.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P4.setText(t);
    }//GEN-LAST:event_Q4ActionPerformed

    private void P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P3ActionPerformed

    private void P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P4ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
        P4.setText("150");
    }//GEN-LAST:event_s4ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
        P4.setText("160");
    }//GEN-LAST:event_m4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void P5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P5ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
        P5.setText("150");
    }//GEN-LAST:event_s5ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
        P5.setText("160");
    }//GEN-LAST:event_m5ActionPerformed

    private void L5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5ActionPerformed
        // TODO add your handling code here:
        P5.setText("170");
    }//GEN-LAST:event_L5ActionPerformed

    private void EL5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL5ActionPerformed
        // TODO add your handling code here:
        P5.setText("180");
    }//GEN-LAST:event_EL5ActionPerformed

    private void Q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P5.getText());
        int q = Integer.parseInt((String) Q5.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P5.setText(t);
    }//GEN-LAST:event_Q5ActionPerformed

    private void P6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P6ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_P6ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
         P6.setText("150");
    }//GEN-LAST:event_s6ActionPerformed

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        // TODO add your handling code here:
        P6.setText("160");
    }//GEN-LAST:event_m6ActionPerformed

    private void L6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L6ActionPerformed
        // TODO add your handling code here:
        P6.setText("170");
    }//GEN-LAST:event_L6ActionPerformed

    private void EL6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL6ActionPerformed
        // TODO add your handling code here:
        P6.setText("180");
    }//GEN-LAST:event_EL6ActionPerformed

    private void Q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q6ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P6.getText());
        int q = Integer.parseInt((String) Q6.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P6.setText(t);
    }//GEN-LAST:event_Q6ActionPerformed

    private void P7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P7ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        // TODO add your handling code here:
        P7.setText("150");
    }//GEN-LAST:event_s7ActionPerformed

    private void m7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m7ActionPerformed
        // TODO add your handling code here:
        P7.setText("160");
    }//GEN-LAST:event_m7ActionPerformed

    private void L7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L7ActionPerformed
        // TODO add your handling code here:
        P7.setText("170");
    }//GEN-LAST:event_L7ActionPerformed

    private void EL7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL7ActionPerformed
        // TODO add your handling code here:
        P7.setText("180");
    }//GEN-LAST:event_EL7ActionPerformed

    private void Q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q7ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P7.getText());
        int q = Integer.parseInt((String) Q7.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P7.setText(t);
    }//GEN-LAST:event_Q7ActionPerformed

    private void P8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P8ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
        // TODO add your handling code here:
        P8.setText("150");
    }//GEN-LAST:event_s8ActionPerformed

    private void m8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m8ActionPerformed
        // TODO add your handling code here:
        P8.setText("160");
    }//GEN-LAST:event_m8ActionPerformed

    private void L8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L8ActionPerformed
        // TODO add your handling code here:
        P8.setText("170");
    }//GEN-LAST:event_L8ActionPerformed

    private void EL8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL8ActionPerformed
        // TODO add your handling code here:
        P8.setText("180");
    }//GEN-LAST:event_EL8ActionPerformed

    private void Q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q8ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P8.getText());
        int q = Integer.parseInt((String) Q8.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P8.setText(t);
        
    }//GEN-LAST:event_Q8ActionPerformed

    private void P9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P9ActionPerformed

    private void m9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m9ActionPerformed
        // TODO add your handling code here:
        P9.setText("160");
    }//GEN-LAST:event_m9ActionPerformed

    private void L9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L9ActionPerformed
        // TODO add your handling code here:
        P9.setText("170");
    }//GEN-LAST:event_L9ActionPerformed

    private void EL9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL9ActionPerformed
        // TODO add your handling code here:
        P9.setText("180");
    }//GEN-LAST:event_EL9ActionPerformed

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
        // TODO add your handling code here:
        P9.setText("150");
    }//GEN-LAST:event_s9ActionPerformed

    private void Q9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q9ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P9.getText());
        int q = Integer.parseInt((String) Q9.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P9.setText(t);
    }//GEN-LAST:event_Q9ActionPerformed

    private void P10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P10ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
        // TODO add your handling code here:
        P10.setText("150");
    }//GEN-LAST:event_s10ActionPerformed

    private void m10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m10ActionPerformed
        // TODO add your handling code here:
        P10.setText("160");
    }//GEN-LAST:event_m10ActionPerformed

    private void L10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L10ActionPerformed
        // TODO add your handling code here:
        P10.setText("170");
    }//GEN-LAST:event_L10ActionPerformed

    private void EL10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL10ActionPerformed
        // TODO add your handling code here:
        P10.setText("180");
    }//GEN-LAST:event_EL10ActionPerformed

    private void Q10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q10ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P10.getText());
        int q = Integer.parseInt((String) Q10.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P10.setText(t);
    }//GEN-LAST:event_Q10ActionPerformed

    private void P11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P11ActionPerformed

    private void L11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L11ActionPerformed
        // TODO add your handling code here:
        P11.setText("170");
    }//GEN-LAST:event_L11ActionPerformed

    private void EL11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL11ActionPerformed
        // TODO add your handling code here:
        P11.setText("180");
    }//GEN-LAST:event_EL11ActionPerformed

    private void Q11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q11ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P11.getText());
        int q = Integer.parseInt((String) Q11.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P11.setText(t);
    }//GEN-LAST:event_Q11ActionPerformed

    private void P12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P12ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        // TODO add your handling code here:
        P12.setText("150");
    }//GEN-LAST:event_s12ActionPerformed

    private void L12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L12ActionPerformed
        // TODO add your handling code here:
        P12.setText("170");
    }//GEN-LAST:event_L12ActionPerformed

    private void EL12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EL12ActionPerformed
        // TODO add your handling code here:
        P12.setText("180");
    }//GEN-LAST:event_EL12ActionPerformed

    private void Q12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q12ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(P12.getText());
        int q = Integer.parseInt((String)Q12.getSelectedItem());
        int total = p * q;
        String t = String.valueOf(total);
        P12.setText(t);
    }//GEN-LAST:event_Q12ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.dispose();
        CoffeeDashboad cd = new CoffeeDashboad();
        cd.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        this.dispose();
        TeaDashBoard td = new TeaDashBoard();
        td.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        this.dispose();
        DrinksDashBoard dD = new DrinksDashBoard();
        dD.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        PastryDashBoard2 pd = new PastryDashBoard2();
        pd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        FoodDashBoard fd = new FoodDashBoard();
        fd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        OrderList ol = new OrderList();
        ol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeDashboad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeDashboad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeDashboad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeDashboad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeDashboad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Americano;
    private javax.swing.ButtonGroup AmericanoBTG;
    private javax.swing.JLabel BackGroundImage;
    private javax.swing.JLabel BackGroundImage2;
    private javax.swing.JPanel Brewed;
    private javax.swing.ButtonGroup BrewedBTG;
    private javax.swing.JPanel Cacao;
    private javax.swing.ButtonGroup CacaoBTG;
    private javax.swing.JPanel Caramel;
    private javax.swing.ButtonGroup CaramelBTG;
    private javax.swing.JLabel CoffeSize14;
    private javax.swing.JLabel CoffeSize15;
    private javax.swing.JLabel CoffeSize16;
    private javax.swing.JLabel CoffeSize17;
    private javax.swing.JLabel CoffeSize18;
    private javax.swing.JLabel CoffeSize19;
    private javax.swing.JLabel CoffeSize20;
    private javax.swing.JLabel CoffeSize21;
    private javax.swing.JLabel CoffeSize22;
    private javax.swing.JLabel CoffeSize23;
    private javax.swing.JLabel CoffeSize25;
    private javax.swing.JLabel CoffeSize26;
    private javax.swing.JLabel CoffeSize8;
    private javax.swing.JLabel CoffeeMenu;
    private javax.swing.JLabel CoffeeName14;
    private javax.swing.JLabel CoffeeName15;
    private javax.swing.JLabel CoffeeName16;
    private javax.swing.JLabel CoffeeName17;
    private javax.swing.JLabel CoffeeName18;
    private javax.swing.JLabel CoffeeName19;
    private javax.swing.JLabel CoffeeName20;
    private javax.swing.JLabel CoffeeName21;
    private javax.swing.JLabel CoffeeName22;
    private javax.swing.JLabel CoffeeName23;
    private javax.swing.JLabel CoffeeName25;
    private javax.swing.JLabel CoffeeName8;
    private javax.swing.JLabel CoffeePrice14;
    private javax.swing.JLabel CoffeePrice15;
    private javax.swing.JLabel CoffeePrice16;
    private javax.swing.JLabel CoffeePrice17;
    private javax.swing.JLabel CoffeePrice18;
    private javax.swing.JLabel CoffeePrice19;
    private javax.swing.JLabel CoffeePrice20;
    private javax.swing.JLabel CoffeePrice21;
    private javax.swing.JLabel CoffeePrice22;
    private javax.swing.JLabel CoffeePrice23;
    private javax.swing.JLabel CoffeePrice25;
    private javax.swing.JLabel CoffeePrice8;
    private javax.swing.JPanel ConPanna;
    private javax.swing.ButtonGroup ConPannaBTG;
    private javax.swing.JPanel Cortado;
    private javax.swing.ButtonGroup CortadoBTG;
    private javax.swing.JPanel DarkChocolate;
    private javax.swing.ButtonGroup DarkChocolateBTG;
    private javax.swing.JCheckBox EL1;
    private javax.swing.JCheckBox EL10;
    private javax.swing.JCheckBox EL11;
    private javax.swing.JCheckBox EL12;
    private javax.swing.JCheckBox EL2;
    private javax.swing.JCheckBox EL3;
    private javax.swing.JCheckBox EL4;
    private javax.swing.JCheckBox EL5;
    private javax.swing.JCheckBox EL6;
    private javax.swing.JCheckBox EL7;
    private javax.swing.JCheckBox EL8;
    private javax.swing.JCheckBox EL9;
    private javax.swing.JPanel Espresso;
    private javax.swing.ButtonGroup EspressoBTG;
    private javax.swing.JPanel FlatWhite;
    private javax.swing.ButtonGroup FlatWhiteBTG;
    private javax.swing.ButtonGroup HazelNutBTG;
    private javax.swing.JPanel Hazelnut;
    private javax.swing.JCheckBox L1;
    private javax.swing.JCheckBox L10;
    private javax.swing.JCheckBox L11;
    private javax.swing.JCheckBox L12;
    private javax.swing.JCheckBox L2;
    private javax.swing.JCheckBox L3;
    private javax.swing.JCheckBox L4;
    private javax.swing.JCheckBox L5;
    private javax.swing.JCheckBox L6;
    private javax.swing.JCheckBox L7;
    private javax.swing.JCheckBox L8;
    private javax.swing.JCheckBox L9;
    private javax.swing.JPanel Latte;
    private javax.swing.ButtonGroup LatteBTG;
    private javax.swing.JTextField P1;
    private javax.swing.JTextField P10;
    private javax.swing.JTextField P11;
    private javax.swing.JTextField P12;
    private javax.swing.JTextField P2;
    private javax.swing.JTextField P3;
    private javax.swing.JTextField P4;
    private javax.swing.JTextField P5;
    private javax.swing.JTextField P6;
    private javax.swing.JTextField P7;
    private javax.swing.JTextField P8;
    private javax.swing.JTextField P9;
    private javax.swing.JComboBox<String> Q1;
    private javax.swing.JComboBox<String> Q10;
    private javax.swing.JComboBox<String> Q11;
    private javax.swing.JComboBox<String> Q12;
    private javax.swing.JComboBox<String> Q2;
    private javax.swing.JComboBox<String> Q3;
    private javax.swing.JComboBox<String> Q4;
    private javax.swing.JComboBox<String> Q5;
    private javax.swing.JComboBox<String> Q6;
    private javax.swing.JComboBox<String> Q7;
    private javax.swing.JComboBox<String> Q8;
    private javax.swing.JComboBox<String> Q9;
    private javax.swing.JPanel WhiteMocha;
    private javax.swing.ButtonGroup WhiteMochaBTG;
    private javax.swing.JButton add1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox m1;
    private javax.swing.JCheckBox m10;
    private javax.swing.JCheckBox m11;
    private javax.swing.JCheckBox m12;
    private javax.swing.JCheckBox m2;
    private javax.swing.JCheckBox m3;
    private javax.swing.JCheckBox m4;
    private javax.swing.JCheckBox m5;
    private javax.swing.JCheckBox m6;
    private javax.swing.JCheckBox m7;
    private javax.swing.JCheckBox m8;
    private javax.swing.JCheckBox m9;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s10;
    private javax.swing.JCheckBox s11;
    private javax.swing.JCheckBox s12;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox s5;
    private javax.swing.JCheckBox s6;
    private javax.swing.JCheckBox s7;
    private javax.swing.JCheckBox s8;
    private javax.swing.JCheckBox s9;
    // End of variables declaration//GEN-END:variables

  
}
