

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marianne
 */
public class FoodDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form FoodDashBoard
     */
    public FoodDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        AlfredoFettuccine = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CoffeeName14 = new javax.swing.JLabel();
        CoffeePrice14 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Add14 = new javax.swing.JButton();
        Bolognese = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CoffeeName15 = new javax.swing.JLabel();
        CoffeePrice15 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Add13 = new javax.swing.JButton();
        Carbonara = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CoffeeName16 = new javax.swing.JLabel();
        CoffeePrice16 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Add15 = new javax.swing.JButton();
        GarlicButterShrimpPasta = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CoffeeName17 = new javax.swing.JLabel();
        CoffeePrice17 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        Add16 = new javax.swing.JButton();
        GnocchiWithPesto = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CoffeeName18 = new javax.swing.JLabel();
        CoffeePrice18 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        Add12 = new javax.swing.JButton();
        MacAndCheese = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        CoffeeName19 = new javax.swing.JLabel();
        CoffeePrice19 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        Add11 = new javax.swing.JButton();
        PastaPrimavera = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        CoffeeName20 = new javax.swing.JLabel();
        CoffeePrice20 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        Add10 = new javax.swing.JButton();
        PenneArrabbiata = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        CoffeeName21 = new javax.swing.JLabel();
        CoffeePrice21 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        Add9 = new javax.swing.JButton();
        Spagheti = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        CoffeeName22 = new javax.swing.JLabel();
        CoffeePrice22 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        Add8 = new javax.swing.JButton();
        TunaPesto = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        CoffeeName23 = new javax.swing.JLabel();
        CoffeePrice23 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        Add7 = new javax.swing.JButton();
        RissottoAllaMilanese = new javax.swing.JPanel();
        CoffeeName24 = new javax.swing.JLabel();
        CoffeePrice24 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Add6 = new javax.swing.JButton();
        OssoBuco = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        CoffeeName25 = new javax.swing.JLabel();
        CoffeePrice25 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        Add5 = new javax.swing.JButton();
        Cannoli = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        CoffeeName26 = new javax.swing.JLabel();
        CoffeePrice26 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox<>();
        Add4 = new javax.swing.JButton();
        Lasagna = new javax.swing.JPanel();
        CoffeeName27 = new javax.swing.JLabel();
        CoffeePrice27 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Add3 = new javax.swing.JButton();
        MagheritaPizza = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        CoffeeName28 = new javax.swing.JLabel();
        CoffeePrice28 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox<>();
        Add2 = new javax.swing.JButton();
        Minestrone = new javax.swing.JPanel();
        CoffeeName29 = new javax.swing.JLabel();
        CoffeePrice29 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Add1 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlfredoFettuccine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AlfredoFettuccine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/alfredo fettuccine.jpg"))); // NOI18N
        AlfredoFettuccine.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName14.setText("Name:");
        AlfredoFettuccine.add(CoffeeName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice14.setText("Price");
        AlfredoFettuccine.add(CoffeePrice14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel71.setText("Quantity");
        AlfredoFettuccine.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel5.setText("Alfredo Fettuccine");
        AlfredoFettuccine.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel6.setText("150");
        AlfredoFettuccine.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        AlfredoFettuccine.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add14.setText("Add");
        AlfredoFettuccine.add(Add14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(AlfredoFettuccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1060, 211, 320));

        Bolognese.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bolognese.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/bolognese.jpg"))); // NOI18N
        Bolognese.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName15.setText("Name:");
        Bolognese.add(CoffeeName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice15.setText("Price");
        Bolognese.add(CoffeePrice15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel72.setText("Quantity");
        Bolognese.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setText("Bolognese");
        Bolognese.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel9.setText("150");
        Bolognese.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Bolognese.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add13.setText("Add");
        Bolognese.add(Add13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(Bolognese, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1060, 211, 320));

        Carbonara.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Carbonara.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/carbonara.jpg"))); // NOI18N
        Carbonara.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName16.setText("Name:");
        Carbonara.add(CoffeeName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice16.setText("Price");
        Carbonara.add(CoffeePrice16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel73.setText("Quantity");
        Carbonara.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel11.setText("Carbonara");
        Carbonara.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel12.setText("150");
        Carbonara.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Carbonara.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add15.setText("Add");
        Carbonara.add(Add15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(Carbonara, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1060, 211, 320));

        GarlicButterShrimpPasta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GarlicButterShrimpPasta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/garlic butter shrimp pasta.jpg"))); // NOI18N
        GarlicButterShrimpPasta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName17.setText("Name:");
        GarlicButterShrimpPasta.add(CoffeeName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice17.setText("Price");
        GarlicButterShrimpPasta.add(CoffeePrice17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel74.setText("Quantity");
        GarlicButterShrimpPasta.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel14.setText("Garlic Butter Shrimp Pasta");
        GarlicButterShrimpPasta.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel15.setText("150");
        GarlicButterShrimpPasta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        GarlicButterShrimpPasta.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add16.setText("Add");
        GarlicButterShrimpPasta.add(Add16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(GarlicButterShrimpPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1060, 211, 320));

        GnocchiWithPesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GnocchiWithPesto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/gnocchi with pesto.jpg"))); // NOI18N
        GnocchiWithPesto.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName18.setText("Name:");
        GnocchiWithPesto.add(CoffeeName18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice18.setText("Price");
        GnocchiWithPesto.add(CoffeePrice18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel75.setText("Quantity");
        GnocchiWithPesto.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel17.setText("Gnocchi with Pesto");
        GnocchiWithPesto.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel18.setText("150");
        GnocchiWithPesto.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        GnocchiWithPesto.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add12.setText("Add");
        GnocchiWithPesto.add(Add12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(GnocchiWithPesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 710, 211, 320));

        MacAndCheese.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MacAndCheese.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/mac and cheese.jpg"))); // NOI18N
        MacAndCheese.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName19.setText("Name:");
        MacAndCheese.add(CoffeeName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice19.setText("Price");
        MacAndCheese.add(CoffeePrice19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel76.setText("Quantity");
        MacAndCheese.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel20.setText("Mac and Cheese");
        MacAndCheese.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel21.setText("150");
        MacAndCheese.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        MacAndCheese.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add11.setText("Add");
        MacAndCheese.add(Add11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(MacAndCheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 710, 211, 320));

        PastaPrimavera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PastaPrimavera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/pasta primavera.jpg"))); // NOI18N
        PastaPrimavera.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName20.setText("Name:");
        PastaPrimavera.add(CoffeeName20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice20.setText("Price");
        PastaPrimavera.add(CoffeePrice20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel77.setText("Quantity");
        PastaPrimavera.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel23.setText("Pasta Primavera");
        PastaPrimavera.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel24.setText("150");
        PastaPrimavera.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        PastaPrimavera.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add10.setText("Add");
        PastaPrimavera.add(Add10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(PastaPrimavera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, 211, 320));

        PenneArrabbiata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PenneArrabbiata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/penne arrabbiata.jpg"))); // NOI18N
        PenneArrabbiata.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName21.setText("Name:");
        PenneArrabbiata.add(CoffeeName21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice21.setText("Price");
        PenneArrabbiata.add(CoffeePrice21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel78.setText("Quantity");
        PenneArrabbiata.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel26.setText("Penne Arrabbiata");
        PenneArrabbiata.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel27.setText("150");
        PenneArrabbiata.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        PenneArrabbiata.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add9.setText("Add");
        PenneArrabbiata.add(Add9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(PenneArrabbiata, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 211, 320));

        Spagheti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Spagheti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/spaghetti.jpg"))); // NOI18N
        Spagheti.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName22.setText("Name:");
        Spagheti.add(CoffeeName22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice22.setText("Price");
        Spagheti.add(CoffeePrice22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel79.setText("Quantity");
        Spagheti.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel29.setText("Spaghetti");
        Spagheti.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel30.setText("150");
        Spagheti.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Spagheti.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add8.setText("Add");
        Spagheti.add(Add8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(Spagheti, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 211, 320));

        TunaPesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TunaPesto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/tuna pesto.jpg"))); // NOI18N
        TunaPesto.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 160));

        CoffeeName23.setText("Name:");
        TunaPesto.add(CoffeeName23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice23.setText("Price");
        TunaPesto.add(CoffeePrice23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel80.setText("Quantity");
        TunaPesto.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel32.setText("Tuna Pesto ");
        TunaPesto.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel33.setText("150");
        TunaPesto.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        TunaPesto.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add7.setText("Add");
        TunaPesto.add(Add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(TunaPesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 211, 320));

        RissottoAllaMilanese.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RissottoAllaMilanese.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoffeeName24.setText("Name:");
        RissottoAllaMilanese.add(CoffeeName24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice24.setText("Price");
        RissottoAllaMilanese.add(CoffeePrice24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel81.setText("Quantity");
        RissottoAllaMilanese.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel35.setText("Rissotto alla Milanese");
        RissottoAllaMilanese.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel36.setText("150");
        RissottoAllaMilanese.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        RissottoAllaMilanese.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/Risotto alla Milanese.jpg"))); // NOI18N
        RissottoAllaMilanese.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        Add6.setText("Add");
        RissottoAllaMilanese.add(Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(RissottoAllaMilanese, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 211, 320));

        OssoBuco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OssoBuco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/Osso Buco.jpg"))); // NOI18N
        OssoBuco.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName25.setText("Name:");
        OssoBuco.add(CoffeeName25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice25.setText("Price");
        OssoBuco.add(CoffeePrice25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel82.setText("Quantity");
        OssoBuco.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel38.setText("Osso Buco");
        OssoBuco.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel39.setText("150");
        OssoBuco.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        OssoBuco.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add5.setText("Add");
        OssoBuco.add(Add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(OssoBuco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 211, 320));

        Cannoli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cannoli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/Cannoli.jpg"))); // NOI18N
        Cannoli.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName26.setText("Name:");
        Cannoli.add(CoffeeName26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice26.setText("Price");
        Cannoli.add(CoffeePrice26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel83.setText("Quantity");
        Cannoli.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel41.setText("Cannoli");
        Cannoli.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel42.setText("150");
        Cannoli.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Cannoli.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add4.setText("Add");
        Cannoli.add(Add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(Cannoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 211, 320));

        Lasagna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Lasagna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoffeeName27.setText("Name:");
        Lasagna.add(CoffeeName27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice27.setText("Price");
        Lasagna.add(CoffeePrice27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel84.setText("Quantity");
        Lasagna.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel44.setText("Lasagna");
        Lasagna.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel45.setText("150");
        Lasagna.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Lasagna.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/Lasagna.jpg"))); // NOI18N
        Lasagna.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 160));

        Add3.setText("Add");
        Lasagna.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(Lasagna, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 211, 310));

        MagheritaPizza.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MagheritaPizza.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/Margherita Pizza.jpg"))); // NOI18N
        MagheritaPizza.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 150));

        CoffeeName28.setText("Name:");
        MagheritaPizza.add(CoffeeName28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice28.setText("Price");
        MagheritaPizza.add(CoffeePrice28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel85.setText("Quantity");
        MagheritaPizza.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel47.setText("Magherita Pizza");
        MagheritaPizza.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel48.setText("150");
        MagheritaPizza.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        MagheritaPizza.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Add2.setText("Add");
        MagheritaPizza.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(MagheritaPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 211, 310));

        Minestrone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Minestrone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CoffeeName29.setText("Name:");
        Minestrone.add(CoffeeName29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        CoffeePrice29.setText("Price");
        Minestrone.add(CoffeePrice29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel86.setText("Quantity");
        Minestrone.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel50.setText("Minestrone");
        Minestrone.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel51.setText("150");
        Minestrone.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Minestrone.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodImage/Minestrone.jpg"))); // NOI18N
        Minestrone.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 160));

        Add1.setText("Add");
        Minestrone.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPanel1.add(Minestrone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 211, 310));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/brgcoffee.jpg"))); // NOI18N
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1410));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1080, 590));

        jLabel43.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Food Menu ");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 50));

        jButton6.setText("Coffee");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        jButton7.setText("Tea");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 70, -1));

        jButton8.setText("Drinks");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, -1, -1));

        jButton9.setText("Pastry");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, -1, -1));

        jButton10.setText("Dishes");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 150, 50));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/brgcoffee.jpg"))); // NOI18N
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        TeaDashBoard td = new TeaDashBoard();
        td.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        CoffeeDashboad cd = new CoffeeDashboad();
        cd.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        DrinksDashBoard dD = new DrinksDashBoard();
        dD.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PastryDashBoard2 pd = new PastryDashBoard2();
        pd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        FoodDashBoard fd = new FoodDashBoard();
        fd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OrderList ol = new OrderList();
        ol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FoodDashBoard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add10;
    private javax.swing.JButton Add11;
    private javax.swing.JButton Add12;
    private javax.swing.JButton Add13;
    private javax.swing.JButton Add14;
    private javax.swing.JButton Add15;
    private javax.swing.JButton Add16;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Add3;
    private javax.swing.JButton Add4;
    private javax.swing.JButton Add5;
    private javax.swing.JButton Add6;
    private javax.swing.JButton Add7;
    private javax.swing.JButton Add8;
    private javax.swing.JButton Add9;
    private javax.swing.JPanel AlfredoFettuccine;
    private javax.swing.JPanel Bolognese;
    private javax.swing.JPanel Cannoli;
    private javax.swing.JPanel Carbonara;
    private javax.swing.JLabel CoffeeName14;
    private javax.swing.JLabel CoffeeName15;
    private javax.swing.JLabel CoffeeName16;
    private javax.swing.JLabel CoffeeName17;
    private javax.swing.JLabel CoffeeName18;
    private javax.swing.JLabel CoffeeName19;
    private javax.swing.JLabel CoffeeName20;
    private javax.swing.JLabel CoffeeName21;
    private javax.swing.JLabel CoffeeName22;
    private javax.swing.JLabel CoffeeName23;
    private javax.swing.JLabel CoffeeName24;
    private javax.swing.JLabel CoffeeName25;
    private javax.swing.JLabel CoffeeName26;
    private javax.swing.JLabel CoffeeName27;
    private javax.swing.JLabel CoffeeName28;
    private javax.swing.JLabel CoffeeName29;
    private javax.swing.JLabel CoffeePrice14;
    private javax.swing.JLabel CoffeePrice15;
    private javax.swing.JLabel CoffeePrice16;
    private javax.swing.JLabel CoffeePrice17;
    private javax.swing.JLabel CoffeePrice18;
    private javax.swing.JLabel CoffeePrice19;
    private javax.swing.JLabel CoffeePrice20;
    private javax.swing.JLabel CoffeePrice21;
    private javax.swing.JLabel CoffeePrice22;
    private javax.swing.JLabel CoffeePrice23;
    private javax.swing.JLabel CoffeePrice24;
    private javax.swing.JLabel CoffeePrice25;
    private javax.swing.JLabel CoffeePrice26;
    private javax.swing.JLabel CoffeePrice27;
    private javax.swing.JLabel CoffeePrice28;
    private javax.swing.JLabel CoffeePrice29;
    private javax.swing.JPanel GarlicButterShrimpPasta;
    private javax.swing.JPanel GnocchiWithPesto;
    private javax.swing.JPanel Lasagna;
    private javax.swing.JPanel MacAndCheese;
    private javax.swing.JPanel MagheritaPizza;
    private javax.swing.JPanel Minestrone;
    private javax.swing.JPanel OssoBuco;
    private javax.swing.JPanel PastaPrimavera;
    private javax.swing.JPanel PenneArrabbiata;
    private javax.swing.JPanel RissottoAllaMilanese;
    private javax.swing.JPanel Spagheti;
    private javax.swing.JPanel TunaPesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
