/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Statement;
import java.sql.DriverManager;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author Marianne
 */
public class CashReceipt extends javax.swing.JFrame {

    /**
     * Creates new form CashReceipt
     * 
     * 
     */
    

    
    public CashReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        iteml1 = new javax.swing.JLabel();
        quantityl1 = new javax.swing.JLabel();
        pricel1 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        Quantitytxt = new javax.swing.JTextField();
        Pricetxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BillNumbertxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BillNumbertxt1 = new javax.swing.JTextField();
        BillNumbertxt2 = new javax.swing.JTextField();
        BillNumbertxt3 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iteml1.setText("Item Name");
        jPanel2.add(iteml1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        quantityl1.setText("Quantity");
        jPanel2.add(quantityl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        pricel1.setText("Price");
        jPanel2.add(pricel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        Nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametxtActionPerformed(evt);
            }
        });
        jPanel2.add(Nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 120, -1));

        Quantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantitytxtActionPerformed(evt);
            }
        });
        jPanel2.add(Quantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 120, -1));
        jPanel2.add(Pricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, -1));

        jButton1.setText("Print");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        jLabel1.setText("Bill Number");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        jPanel2.add(BillNumbertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, -1));

        jLabel2.setText("Status");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("Customer ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setText("Order ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel2.add(BillNumbertxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 120, -1));

        BillNumbertxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillNumbertxt2ActionPerformed(evt);
            }
        });
        jPanel2.add(BillNumbertxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, -1));
        jPanel2.add(BillNumbertxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NametxtActionPerformed

    private void QuantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantitytxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BillNumbertxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillNumbertxt2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_BillNumbertxt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BillNumbertxt;
    private javax.swing.JTextField BillNumbertxt1;
    private javax.swing.JTextField BillNumbertxt2;
    private javax.swing.JTextField BillNumbertxt3;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField Pricetxt;
    private javax.swing.JTextField Quantitytxt;
    private javax.swing.JLabel iteml1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pricel1;
    private javax.swing.JLabel quantityl1;
    // End of variables declaration//GEN-END:variables
}
