/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.util.Random;


/**
 *
 * @author Marianne
 */
public class HomePage extends javax.swing.JFrame {       
        
       Random random = new Random();
       int randomInt = random.nextInt(10000);
       
        
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();          
        OrderID.setText("Order ID " + randomInt);
        OrderID.setVisible(true);
         if(coffeeBtn.isEnabled()){
             
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScollContainer = new javax.swing.JPanel();
        FeaturedFood = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        GarlicButterShrimpPasta = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Lasagna = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        OssoBuco = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        AlfredoFettuchini = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Cannoli = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        FeaturedCoffee = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        Cappucino = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FlatWhite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cacao = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ConPanna = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Latte = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FeaturedTea = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        OolongTea = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        EarlyGreyTea = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        HibiscusTea = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        WhiteTea = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        JasmineTea = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        FeaturedDrinks = new javax.swing.JScrollPane();
        jPanel21 = new javax.swing.JPanel();
        BloodyMaryCoctail = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        MintJulep = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        HotChocolate = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        BubleTea = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        MangoLassi = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OrderID = new javax.swing.JLabel();
        LogoName1 = new javax.swing.JLabel();
        coffeeBtn = new javax.swing.JButton();
        TeaBtn = new javax.swing.JButton();
        DrinksBtn = new javax.swing.JButton();
        FoodBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        PastriesBtn = new javax.swing.JButton();
        HomepageBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ScollContainer.setBackground(new java.awt.Color(160, 120, 86));
        ScollContainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ScollContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(203, 183, 153));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GarlicButterShrimpPasta.setBackground(new java.awt.Color(255, 255, 255));
        GarlicButterShrimpPasta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/garlic butter shrimp pasta.jpg"))); // NOI18N
        GarlicButterShrimpPasta.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 140));

        jLabel42.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel42.setText("Garlic Butter Shrimp Pasta");
        GarlicButterShrimpPasta.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 30));

        jPanel3.add(GarlicButterShrimpPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 240, 170));

        Lasagna.setBackground(new java.awt.Color(255, 255, 255));
        Lasagna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lasagna.jpg"))); // NOI18N
        Lasagna.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        jLabel34.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel34.setText("Lasagna");
        Lasagna.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 30));

        jPanel3.add(Lasagna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        OssoBuco.setBackground(new java.awt.Color(255, 255, 255));
        OssoBuco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Osso Buco.jpg"))); // NOI18N
        OssoBuco.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        jLabel36.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel36.setText("Osso Buco");
        OssoBuco.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 30));

        jPanel3.add(OssoBuco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        AlfredoFettuchini.setBackground(new java.awt.Color(255, 255, 255));
        AlfredoFettuchini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alfredo fettuccine.jpg"))); // NOI18N
        AlfredoFettuchini.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        jLabel38.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel38.setText("Alfredo Fettuchini");
        AlfredoFettuchini.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 30));

        jPanel3.add(AlfredoFettuchini, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        Cannoli.setBackground(new java.awt.Color(255, 255, 255));
        Cannoli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cannoli.jpg"))); // NOI18N
        Cannoli.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 140));

        jLabel40.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel40.setText("Cannoli");
        Cannoli.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 30));

        jPanel3.add(Cannoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        FeaturedFood.setViewportView(jPanel3);

        ScollContainer.add(FeaturedFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1010, 930, 240));

        jPanel9.setBackground(new java.awt.Color(203, 183, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cappucino.setBackground(new java.awt.Color(255, 255, 255));
        Cappucino.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cappuccino coffee.jpg"))); // NOI18N
        Cappucino.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel14.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel14.setText("Cappuccino");
        Cappucino.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel9.add(Cappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        FlatWhite.setBackground(new java.awt.Color(255, 255, 255));
        FlatWhite.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Flat white coffee.jpg"))); // NOI18N
        FlatWhite.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("Flat White");
        FlatWhite.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel9.add(FlatWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        Cacao.setBackground(new java.awt.Color(255, 255, 255));
        Cacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cacao.jpg"))); // NOI18N
        Cacao.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("Cacao");
        Cacao.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel9.add(Cacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        ConPanna.setBackground(new java.awt.Color(255, 255, 255));
        ConPanna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Con panna coffee.jpg"))); // NOI18N
        ConPanna.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel10.setText("Con Panna ");
        ConPanna.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel9.add(ConPanna, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        Latte.setBackground(new java.awt.Color(255, 255, 255));
        Latte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Latte coffee.jpg"))); // NOI18N
        Latte.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel12.setText("Latte");
        Latte.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel9.add(Latte, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        FeaturedCoffee.setViewportView(jPanel9);

        ScollContainer.add(FeaturedCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 930, 240));

        jPanel15.setBackground(new java.awt.Color(203, 183, 153));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OolongTea.setBackground(new java.awt.Color(255, 255, 255));
        OolongTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Oolong Tea.jpg"))); // NOI18N
        OolongTea.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel44.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel44.setText("Oolong Tea");
        OolongTea.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel15.add(OolongTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        EarlyGreyTea.setBackground(new java.awt.Color(255, 255, 255));
        EarlyGreyTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Earl Grey.jpg"))); // NOI18N
        EarlyGreyTea.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel16.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel16.setText("Early Grey Tea");
        EarlyGreyTea.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel15.add(EarlyGreyTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        HibiscusTea.setBackground(new java.awt.Color(255, 255, 255));
        HibiscusTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hibiscus Tea.jpg"))); // NOI18N
        HibiscusTea.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel18.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel18.setText("Hibiscus Tea");
        HibiscusTea.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel15.add(HibiscusTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        WhiteTea.setBackground(new java.awt.Color(255, 255, 255));
        WhiteTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White Tea.jpg"))); // NOI18N
        WhiteTea.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel20.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel20.setText("White Tea");
        WhiteTea.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel15.add(WhiteTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        JasmineTea.setBackground(new java.awt.Color(255, 255, 255));
        JasmineTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Jasmine Tea.jpg"))); // NOI18N
        JasmineTea.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel22.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel22.setText("Jasmine Tea");
        JasmineTea.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel15.add(JasmineTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        FeaturedTea.setViewportView(jPanel15);

        ScollContainer.add(FeaturedTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 930, 230));

        jPanel21.setBackground(new java.awt.Color(203, 183, 153));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BloodyMaryCoctail.setBackground(new java.awt.Color(255, 255, 255));
        BloodyMaryCoctail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bloody_Mary_Coctail.jpg"))); // NOI18N
        BloodyMaryCoctail.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel32.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel32.setText("Bloody Mary Coctail");
        BloodyMaryCoctail.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel21.add(BloodyMaryCoctail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        MintJulep.setBackground(new java.awt.Color(255, 255, 255));
        MintJulep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mint Julep.jpg"))); // NOI18N
        MintJulep.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel24.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel24.setText("Mint Julep");
        MintJulep.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel21.add(MintJulep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        HotChocolate.setBackground(new java.awt.Color(255, 255, 255));
        HotChocolate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hot Chocolate.jpg"))); // NOI18N
        HotChocolate.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel26.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel26.setText("Hot Chocolate");
        HotChocolate.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel21.add(HotChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        BubleTea.setBackground(new java.awt.Color(255, 255, 255));
        BubleTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bubble-Tea.png"))); // NOI18N
        BubleTea.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jLabel28.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel28.setText("Buble Tea");
        BubleTea.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel21.add(BubleTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        MangoLassi.setBackground(new java.awt.Color(255, 255, 255));
        MangoLassi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mango-Lassi.jpg"))); // NOI18N
        MangoLassi.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 370, 130));

        jLabel29.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel29.setText("Mango Lassi");
        MangoLassi.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 40));

        jPanel21.add(MangoLassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        FeaturedDrinks.setViewportView(jPanel21);

        ScollContainer.add(FeaturedDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 930, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Featured Coffee");
        ScollContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 292, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Featured Food");
        ScollContainer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 960, 292, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Featured Drinks");
        ScollContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 292, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Featured Tea");
        ScollContainer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 292, 40));

        jScrollPane1.setViewportView(ScollContainer);

        Container.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1050, 600));

        OrderID.setBackground(new java.awt.Color(255, 255, 255));
        OrderID.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        OrderID.setForeground(new java.awt.Color(255, 255, 255));
        OrderID.setToolTipText("");
        Container.add(OrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));

        LogoName1.setBackground(new java.awt.Color(255, 255, 255));
        LogoName1.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LogoName1.setForeground(new java.awt.Color(255, 255, 255));
        LogoName1.setText("Elysian");
        LogoName1.setToolTipText("");
        Container.add(LogoName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 229, 76));

        coffeeBtn.setText("Coffee");
        coffeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeBtnActionPerformed(evt);
            }
        });
        Container.add(coffeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        TeaBtn.setText("Tea");
        TeaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaBtnActionPerformed(evt);
            }
        });
        Container.add(TeaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        DrinksBtn.setText("Drinks");
        DrinksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksBtnActionPerformed(evt);
            }
        });
        Container.add(DrinksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        FoodBtn.setText("Dishes");
        FoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtnActionPerformed(evt);
            }
        });
        Container.add(FoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        AdminBtn.setText("Admin");
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });
        Container.add(AdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        PastriesBtn.setText("Pastries");
        PastriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastriesBtnActionPerformed(evt);
            }
        });
        Container.add(PastriesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        HomepageBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brgcoffee.jpg"))); // NOI18N
        Container.add(HomepageBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 690));

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtnActionPerformed
        FoodDashBoard fd = new FoodDashBoard();
        fd.setVisible(true);
        //HomePage hp = new HomePage();
        //hp.setVisible(false);
        this.dispose();
      
    }//GEN-LAST:event_FoodBtnActionPerformed

    private void coffeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeBtnActionPerformed
        this.dispose();
        //HomePage hp = new HomePage();
        //hp.setVisible(false);
        //hp.dispose();
        CoffeeDashboad cd = new CoffeeDashboad();
        cd.setVisible(true);
        
    }//GEN-LAST:event_coffeeBtnActionPerformed

    private void TeaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TeaDashBoard td = new TeaDashBoard();
        td.setVisible(true);
        //HomePage hp = new HomePage();
        //hp.setVisible(false);
    }//GEN-LAST:event_TeaBtnActionPerformed

    private void DrinksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DrinksDashBoard dD = new DrinksDashBoard();
        dD.setVisible(true);
       // HomePage hp = new HomePage();
        //hp.setVisible(false);
        //hp.dispose();
    }//GEN-LAST:event_DrinksBtnActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
       // AdminDashBoard ad = new AdminDashBoard();
      //  ad.setVisible(true);
       
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void PastriesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastriesBtnActionPerformed
        // TODO add your handling code here:
        PastryDashBoard2 pd = new PastryDashBoard2();
        pd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PastriesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JPanel AlfredoFettuchini;
    private javax.swing.JPanel BloodyMaryCoctail;
    private javax.swing.JPanel BubleTea;
    private javax.swing.JPanel Cacao;
    private javax.swing.JPanel Cannoli;
    private javax.swing.JPanel Cappucino;
    private javax.swing.JPanel ConPanna;
    private javax.swing.JPanel Container;
    private javax.swing.JButton DrinksBtn;
    private javax.swing.JPanel EarlyGreyTea;
    private javax.swing.JScrollPane FeaturedCoffee;
    private javax.swing.JScrollPane FeaturedDrinks;
    private javax.swing.JScrollPane FeaturedFood;
    private javax.swing.JScrollPane FeaturedTea;
    private javax.swing.JPanel FlatWhite;
    private javax.swing.JButton FoodBtn;
    private javax.swing.JPanel GarlicButterShrimpPasta;
    private javax.swing.JPanel HibiscusTea;
    private javax.swing.JLabel HomepageBG;
    private javax.swing.JPanel HotChocolate;
    private javax.swing.JPanel JasmineTea;
    private javax.swing.JPanel Lasagna;
    private javax.swing.JPanel Latte;
    private javax.swing.JLabel LogoName1;
    private javax.swing.JPanel MangoLassi;
    private javax.swing.JPanel MintJulep;
    private javax.swing.JPanel OolongTea;
    private javax.swing.JLabel OrderID;
    private javax.swing.JPanel OssoBuco;
    private javax.swing.JButton PastriesBtn;
    private javax.swing.JPanel ScollContainer;
    private javax.swing.JButton TeaBtn;
    private javax.swing.JPanel WhiteTea;
    private javax.swing.JButton coffeeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables




}
