/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Marianne
 */
public class PastryDashBoard2 extends javax.swing.JFrame {

    /**
     * Creates new form PastryDashBoard2
     */
    public PastryDashBoard2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PastriesDashBoard = new javax.swing.JPanel();
        NextButton = new javax.swing.JButton();
        TotalButton = new javax.swing.JButton();
        PreviousBtn = new javax.swing.JButton();
        CoffeeCinamonRolls = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Danish = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Baklava = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel103 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        BerryCreamPuff = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel102 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Macarons = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel101 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        KouignAmann = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel104 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Churros = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        CaramelEcliar = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Croisant = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel96 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        SconeButtery = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox<>();
        jLabel95 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        Palmiers = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel98 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        Madeleine = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox<>();
        jLabel99 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        MilleFeuille = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jLabel100 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        Pestelito = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel97 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        Tart = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        ToasterStrudel = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox<>();
        jLabel93 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        HomePageBtn = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        bgi = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        bgi2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PastriesDashBoard.setBackground(new java.awt.Color(255, 255, 255));
        PastriesDashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        PastriesDashBoard.add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 1540, 80, 35));

        TotalButton.setText("Total");
        TotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButtonActionPerformed(evt);
            }
        });
        PastriesDashBoard.add(TotalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 1540, 80, 35));

        PreviousBtn.setText("Previous");
        PreviousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousBtnActionPerformed(evt);
            }
        });
        PastriesDashBoard.add(PreviousBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 1540, 80, 35));

        CoffeeCinamonRolls.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CoffeeCinamonRolls.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Coffee-Cinnamon-Rolls.jpg"))); // NOI18N
        CoffeeCinamonRolls.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel14.setText("Name");
        CoffeeCinamonRolls.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel15.setText("Coffee Cinnamon Rolls");
        CoffeeCinamonRolls.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel16.setText("Quantity");
        CoffeeCinamonRolls.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        CoffeeCinamonRolls.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel111.setText("Price");
        CoffeeCinamonRolls.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel112.setText("70");
        CoffeeCinamonRolls.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jButton1.setText("Add");
        CoffeeCinamonRolls.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(CoffeeCinamonRolls, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 350));

        Danish.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Danish.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Danish Pastries.jpg"))); // NOI18N
        Danish.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel22.setText("Name");
        Danish.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel23.setText("Danish ");
        Danish.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel24.setText("Quantity");
        Danish.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Danish.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel107.setText("Price");
        Danish.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel108.setText("60");
        Danish.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jButton2.setText("Add");
        Danish.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Danish, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 340, 350));

        Baklava.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Baklava.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Baklava.jpg"))); // NOI18N
        Baklava.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel26.setText("Name");
        Baklava.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel27.setText("Baklava");
        Baklava.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel28.setText("Quantity");
        Baklava.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Baklava.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel103.setText("Price");
        Baklava.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel20.setText("100");
        Baklava.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton3.setText("Add");
        Baklava.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Baklava, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 340, 350));

        BerryCreamPuff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BerryCreamPuff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Berry Cream Puff.jpg"))); // NOI18N
        BerryCreamPuff.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel30.setText("Name");
        BerryCreamPuff.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel31.setText("Berry Cream Puff");
        BerryCreamPuff.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel32.setText("Quantity");
        BerryCreamPuff.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        BerryCreamPuff.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel102.setText("Price");
        BerryCreamPuff.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel19.setText("90");
        BerryCreamPuff.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton4.setText("Add");
        BerryCreamPuff.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(BerryCreamPuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 340, 350));

        Macarons.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Macarons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Macarons.jpg"))); // NOI18N
        Macarons.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel34.setText("Name");
        Macarons.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel35.setText("Macarons");
        Macarons.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel36.setText("Quantity");
        Macarons.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Macarons.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel101.setText("Price");
        Macarons.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel18.setText("150 for a box contains 6 pcs ");
        Macarons.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton8.setText("Add");
        Macarons.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        PastriesDashBoard.add(Macarons, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 340, 350));

        KouignAmann.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KouignAmann.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Kouign-Amann.jpg"))); // NOI18N
        KouignAmann.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel38.setText("Name");
        KouignAmann.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel39.setText("Kouign Amann");
        KouignAmann.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel40.setText("Quantity");
        KouignAmann.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        KouignAmann.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel104.setText("Price");
        KouignAmann.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel73.setText("150");
        KouignAmann.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jButton7.setText("Add");
        KouignAmann.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(KouignAmann, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 340, 350));

        Churros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Churros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/churros.jpg"))); // NOI18N
        Churros.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel42.setText("Name");
        Churros.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel43.setText("Churros ");
        Churros.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel44.setText("Quantity");
        Churros.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Churros.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel105.setText("Price");
        Churros.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel106.setText("50");
        Churros.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jButton6.setText("Add");
        Churros.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Churros, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 340, 350));

        CaramelEcliar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CaramelEcliar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caramel-eclair.jpg"))); // NOI18N
        CaramelEcliar.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel46.setText("Name");
        CaramelEcliar.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel47.setText("Caramel Ecliar ");
        CaramelEcliar.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel48.setText("Quantity");
        CaramelEcliar.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        CaramelEcliar.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel109.setText("Price");
        CaramelEcliar.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel110.setText("120");
        CaramelEcliar.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton5.setText("Add");
        CaramelEcliar.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(CaramelEcliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 340, 350));

        Croisant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Croisant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/croisant.png"))); // NOI18N
        Croisant.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel50.setText("Name");
        Croisant.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel51.setText("Croisant ");
        Croisant.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel52.setText("Quantity");
        Croisant.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Croisant.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel96.setText("Price");
        Croisant.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel9.setText("80");
        Croisant.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton9.setText("Add");
        Croisant.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Croisant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, 340, 350));

        SconeButtery.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SconeButtery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Scone-Buttery.jpg"))); // NOI18N
        SconeButtery.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel54.setText("Name");
        SconeButtery.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel55.setText("Scone Buttery");
        SconeButtery.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel56.setText("Quantity");
        SconeButtery.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        SconeButtery.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel95.setText("Price");
        SconeButtery.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel8.setText("50");
        SconeButtery.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jButton10.setText("Add");
        SconeButtery.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(SconeButtery, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 770, 340, 350));

        Palmiers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Palmiers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Palmiers.jpg"))); // NOI18N
        Palmiers.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel58.setText("Name");
        Palmiers.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel59.setText("Palmiers");
        Palmiers.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel60.setText("Quantity");
        Palmiers.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Palmiers.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel98.setText("Price");
        Palmiers.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel11.setText("80");
        Palmiers.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton11.setText("Add");
        Palmiers.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Palmiers, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 770, 340, 350));

        Madeleine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Madeleine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Madeleine.jpg"))); // NOI18N
        Madeleine.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel62.setText("Name");
        Madeleine.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel63.setText("Madeleine");
        Madeleine.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel64.setText("Quantity");
        Madeleine.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Madeleine.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel99.setText("Price");
        Madeleine.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel12.setText("50");
        Madeleine.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton12.setText("Add");
        Madeleine.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Madeleine, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 770, 340, 350));

        MilleFeuille.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MilleFeuille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mille-Feuille.jpg"))); // NOI18N
        MilleFeuille.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel66.setText("Name");
        MilleFeuille.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel67.setText("Mille Feuille");
        MilleFeuille.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel68.setText("Quantity");
        MilleFeuille.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        MilleFeuille.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel100.setText("Price");
        MilleFeuille.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel17.setText("150");
        MilleFeuille.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton16.setText("Add");
        MilleFeuille.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(MilleFeuille, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 1150, 340, 350));

        Pestelito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Pestelito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pastelito.jpg"))); // NOI18N
        Pestelito.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel70.setText("Name");
        Pestelito.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel71.setText("Pastelito ");
        Pestelito.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel72.setText("Quantity");
        Pestelito.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Pestelito.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel97.setText("Price");
        Pestelito.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel10.setText("70");
        Pestelito.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jButton15.setText("Add");
        Pestelito.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Pestelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1150, 340, 350));

        Tart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Tart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setText("Name");
        Tart.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel75.setText("Tart ");
        Tart.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel76.setText("Quantity");
        Tart.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Tart.add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tart.jpg"))); // NOI18N
        Tart.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel94.setText("Price");
        Tart.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel7.setText("120");
        Tart.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 30, -1));

        jButton14.setText("Add");
        Tart.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(Tart, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1150, 340, 350));

        ToasterStrudel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ToasterStrudel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Toaster-Strudel.jpg"))); // NOI18N
        ToasterStrudel.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));

        jLabel78.setText("Name");
        ToasterStrudel.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel79.setText("Toaster Strudel");
        ToasterStrudel.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel80.setText("Price");
        ToasterStrudel.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        ToasterStrudel.add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel93.setText("Quantity");
        ToasterStrudel.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel6.setText("80");
        ToasterStrudel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 30, -1));

        jButton13.setText("Add");
        ToasterStrudel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        PastriesDashBoard.add(ToasterStrudel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1150, 340, 350));

        HomePageBtn.setText("Home");
        HomePageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageBtnActionPerformed(evt);
            }
        });
        PastriesDashBoard.add(HomePageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 1540, 80, 35));

        jButton17.setText("Coffee");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        PastriesDashBoard.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1520, -1, -1));

        jButton18.setText("Tea");
        PastriesDashBoard.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1560, 70, -1));

        jButton19.setText("Drinks");
        PastriesDashBoard.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1520, -1, -1));

        jButton20.setText("Pastry");
        PastriesDashBoard.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 1560, -1, -1));

        jButton21.setText("Dishes");
        PastriesDashBoard.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1540, -1, -1));

        bgi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brgcoffee.jpg"))); // NOI18N
        PastriesDashBoard.add(bgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1480, 1610));

        jScrollPane1.setViewportView(PastriesDashBoard);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1230, 590));
        jScrollPane1.getAccessibleContext().setAccessibleName("");

        jLabel81.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Pastries Menu ");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 160, 50));

        bgi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brgcoffee.jpg"))); // NOI18N
        getContentPane().add(bgi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 2740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageBtnActionPerformed
       this.dispose();
       HomePage hp = new HomePage();
       hp.setVisible(true);
    }//GEN-LAST:event_HomePageBtnActionPerformed

    private void PreviousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousBtnActionPerformed
        // TODO add your handling code here:
        FoodDashBoard fd = new FoodDashBoard();
        fd.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_PreviousBtnActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void TotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButtonActionPerformed
        OrderList ol = new OrderList();
        ol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TotalButtonActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.dispose();
        CoffeeDashboad cd = new CoffeeDashboad();
        cd.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PastryDashBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PastryDashBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PastryDashBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PastryDashBoard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PastryDashBoard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Baklava;
    private javax.swing.JPanel BerryCreamPuff;
    private javax.swing.JPanel CaramelEcliar;
    private javax.swing.JPanel Churros;
    private javax.swing.JPanel CoffeeCinamonRolls;
    private javax.swing.JPanel Croisant;
    private javax.swing.JPanel Danish;
    private javax.swing.JButton HomePageBtn;
    private javax.swing.JPanel KouignAmann;
    private javax.swing.JPanel Macarons;
    private javax.swing.JPanel Madeleine;
    private javax.swing.JPanel MilleFeuille;
    private javax.swing.JButton NextButton;
    private javax.swing.JPanel Palmiers;
    private javax.swing.JPanel PastriesDashBoard;
    private javax.swing.JPanel Pestelito;
    private javax.swing.JButton PreviousBtn;
    private javax.swing.JPanel SconeButtery;
    private javax.swing.JPanel Tart;
    private javax.swing.JPanel ToasterStrudel;
    private javax.swing.JButton TotalButton;
    private javax.swing.JLabel bgi;
    private javax.swing.JLabel bgi2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
